dataset:
  in_channels: 1
  data_scaling: True
  batch_sizes:
    stage1: 16 #128
    stage2: 16
    stage_fid_enhancer: 16
  num_workers: 0

exp_params:
  LR: 0.001

trainer_params:
  max_steps:
    stage1: 50000
    stage2: 50000
    stage_fid_enhancer: 10000
  val_check_interval:
    stage1: 5000
    stage2: 5000
    stage_fid_enhancer: 100

encoder:
  dim: 128
  n_resnet_blocks: 2
  downsampled_width:
    lf: 8 #32 #8
    hf: 32

decoder:
  dim: 128
  n_resnet_blocks: 2


VQ-VAE:
  n_fft: 4
  codebook_sizes:
    lf: 32
    hf: 32

MaskGIT:
  choice_temperatures: # for masking
    lf: 4
    hf: 4
  T: 10
  prior_model_l:
    hidden_dim: 128
    n_layers: 4
    heads: 2
    ff_mult: 1
    use_rmsnorm: True
    p_unconditional: 0.2
    dropout: 0.3
  prior_model_h:
    hidden_dim: 32
    n_layers: 1
    heads: 1
    ff_mult: 1
    use_rmsnorm: True
    p_unconditional: 0.2
    dropout: 0.5
  ESS:
    use: False
    error_ratio_ma_rate: 0.3

class_guidance:
  guidance_scale: 1.

fidelity_enhancer:
  dim: 8
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  resnet_block_groups: 4
  dropout: 0.5

evaluation:
  batch_size: 32
  min_num_gen_samples: 1024